name: Full Stack CI

on:
  push:
    branches:
      - main

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/notebook-api
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./backend/notebook-api/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  frontend-build:
    runs-on: ubuntu-latest
    needs: backend-build-and-test
    defaults:
      run:
        working-directory: ./frontend/notebook-next
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./frontend/notebook-next/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
